version: '3'

tasks:
  lint:
    description: Lint the code
    cmds:
    - uv run mypy ./gqlauth
  test:
    description: Run tests
    dir: "./tests"
    cmds:
      - cd testproject && uv run  migrate.py
      - uv run pytest --ds=tests.testproject.settings -m 'not settings_b' --cov=gqlauth --cov-report=xml
      - uv run pytest --ds=tests.testproject.settings_b -m "not default_user" --cov=gqlauth --cov-report=xml --cov-append


  serve:
    description: Serve the documentation
    cmds:
      - uv run docs/pre_build.py
      - uv run mkdocs serve

  deploy_docs:
    description: Deploy the documentation
    cmds:
      - uv run docs/pre_build.py
      - uv run mkdocs build
      - uv run mkdocs gh-deploy
