"""
Django settings for tzv5hob project.

Generated by 'django-administrator startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
from django.conf import settings as django_settings
from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# TODO See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# ! SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r-5-iq74f(hua%w+t6iesv_#u*kk8-vkw1qw76emcwe@91$%wr'

# ! SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',  # NOTE Required for GraphQL
    'django_extensions',
    'phonenumber_field',
    'strawberry.django',
    'strawberry_django_jwt.refresh_token',
    'gqlauth',  # NOTE authantication with jwt
]

AUTH_USER_MODEL = 'users.CustomUser'


GRAPHQL_JWT = {
    "JWT_VERIFY_EXPIRATION": True,
    "JWT_LONG_RUNNING_REFRESH_TOKEN": True,
    "JWT_ALLOW_ANY_CLASSES": [
        # mutations
        "gqlauth.mutations.Register",
        "gqlauth.mutations.VerifyAccount",
        "gqlauth.mutations.ResendActivationEmail",
        "gqlauth.mutations.SendPasswordResetEmail",
        "gqlauth.mutations.PasswordReset",
        "gqlauth.mutations.ObtainJSONWebToken",
        "gqlauth.mutations.VerifyToken",
        "gqlauth.mutations.RefreshToken",
        "gqlauth.mutations.RevokeToken",
        "gqlauth.mutations.VerifySecondaryEmail"
        # relay
        "gqlauth.relay.Register",
        "gqlauth.relay.VerifyAccount",
        "gqlauth.relay.ResendActivationEmail",
        "gqlauth.relay.SendPasswordResetEmail",
        "gqlauth.relay.PasswordReset",
        "gqlauth.relay.ObtainJSONWebToken",
        "gqlauth.relay.VerifyToken",
        "gqlauth.relay.RefreshToken",
        "gqlauth.relay.RevokeToken",
        "gqlauth.relay.VerifySecondaryEmail",
    ],
}

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # required by strawberry jwt
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tzv5hob.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tzv5hob.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3"}}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'gqlauth.backends.GraphQLAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
