# Generated by Django 4.1.7 on 2023-04-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("color", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("is_eaten", models.BooleanField(default=False)),
            ],
            options={
                "permissions": [("can_eat", "can eat apples")],
            },
        ),
    ]
