# Generated by Django 3.2.12 on 2022-03-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsprovider', '0002_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('refresh_token', '0002_auto_20190130_0900'),
        ('gqlauth', '0002_userrelay_userstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRelay',
        ),
    ]
