"""
- get class names and docstrings as context variables into the docs
- copy [CONTRIBUTORS, CHANGES, CONTRIBUTING] files to the docs dir
"""

from pathlib import Path
import re
import shutil

if __name__ == "__main__":

    # copy mixins file from .py to .yml
    root_dir = Path(__file__).parent.parent
    source = root_dir / "gqlauth/user/resolvers.py"
    destination = root_dir / "docs/data/api.yml"
    dest = shutil.copyfile(source, destination)

    # get the text content
    with open(destination) as file:
        text = file.read()

    # extract each class and docstring
    pattern = re.compile(
        'class\\s(?P<class>\\w*)Mixin[\\w|\\(|\\)]+:\n\\s*"""(?P<doc>[^*]*)"""',
        re.S | re.M,
    )
    matches = re.findall(pattern, text)

    # build the yaml string
    yaml_strings = ["# this file is auto generated by the pre_docs_script.py", ""]
    for m in matches:
        class_name, docstring = m
        yaml_strings.append(class_name + ": |" + docstring)
    yaml_string = "\n".join(yaml_strings)

    # write the file
    with open(destination, "w") as file:
        file.write(yaml_string)

    # copy files from project root to docs dir
    files = ["CONTRIBUTORS.md", "CHANGES.md", "CONTRIBUTING.md"]
    dest = ["contributors.md", "changelog.md", "contributing.md"]
    for index, file in enumerate(files):
        shutil.copyfile(root_dir / file, root_dir / "docs" / dest[index])
