"""
- get class names and docstrings as context variables into the docs
- copy [CONTRIBUTORS, CHANGES, CONTRIBUTING] files to the docs dir
"""

import os
from pathlib import Path
import shutil
import re


# copy mixins file from .py to .yml
current_dir = Path(__file__).parent.parent
source = current_dir / "gqlauth/bases/mixins.py"
destination = current_dir / "docs/data/api.yml"
dest = shutil.copyfile(source, destination)

# get the text content
with open(destination, "r") as file:
    text = file.read()

# extract each class and docstring
pattern = re.compile(
    'class\s(?P<class>\w*)Mixin[\w|\(|\)]+:\n\s*"""(?P<doc>[^*]*)"""',
    re.S | re.M,
)
matches = re.findall(pattern, text)

# build the yaml string
yaml_strings = ["# this file is auto generated by the pre_docs_script.py", ""]
for m in matches:
    class_name, docstring = m
    yaml_strings.append(class_name + ": |" + docstring)
yaml_string = "\n".join(yaml_strings)

# write the file
with open(destination, "w") as file:
    file.write(yaml_string)


# copy files from project root to docs dir
files = ["CONTRIBUTORS.md", "CHANGES.md", "CONTRIBUTING.md"]
dest = ["contributors.md", "changelog.md", "contributing.md"]
for index, file in enumerate(files):
    shutil.copyfile(current_dir / file, current_dir / "docs" / dest[index])


from pydoc_markdown.interfaces import Context
from pydoc_markdown.contrib.loaders.python import PythonLoader
from pydoc_markdown.contrib.renderers.markdown import MarkdownRenderer

context = Context(directory=source)
loader = PythonLoader(search_path=['src'])
renderer = MarkdownRenderer(render_module_header=False)

loader.init(context)
renderer.init(context)

modules = loader.load()
print(renderer.render_to_string(modules))