name: 🫸 Bot comment

on:
  pull_request_target:
    types: [synchronize, reopened, opened, ready_for_review]
    branches:
      - main
    paths:
      - "gqlauth/**"
      - ".github/workflows/bot_comment.yml"
      - "RELEASE.md"

jobs:
  bot_comment:
    name: Create or update bot status comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.12"
      - name: Install deps
        run: uv sync --all-extras --frozen

      - name: upload comment
        run: cd .github && uv run python -m workflows.management bot_comment
        env:
          PR_NUMBER: ${{ github.event.number }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
