name: 🦺 MyPy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "gqlauth/**"
      - "tests/**"
      - ".github/workflows/mypy.yml"
env:
  IS_GITHUB_ACTION: 1

jobs:
  mypy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]


    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          python-version: "3.12"
      - name: Install deps
        run: uv sync --all-extras --frozen

      - name: mypy checks
        run: uv run mypy ./gqlauth
